development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: demo_production
  username: demouser
  password: demopswd
  hostname: 127.0.0.1
  port: 3306